version: '3'

services:
    node_server:
        container_name: node_server
        restart: always
        build: .
        ports:
            - "3000:3000"
        links:
            - db_mongo
        volumes:
            - .:/usr/src/app

    db_mongo:
        container_name: db_mongo
        image: mongo:6.0.2
        ports:
            - "27018:27017"
        volumes:
            - ./mongo/data:/data/db
        logging:
            driver: none
        command: mongod --quiet --logpath /dev/null 