version: '3'

services:
    node_server:
        container_name: node_server
        restart: always
        build: 
            context: ./app
        command: npm run start
        ports:
            - "3000:3000"
        links:
            - db_mongo
        volumes:
            - .:/usr/src/app
        environment:
            URI_MONGO: "${URI_MONGO}"

    db_mongo:
        container_name: db_mongo
        restart: always
        image: mongo:6.0.2
        ports:
            - "27018:27017"
        volumes:
            - ./app/mongo/data:/data/db
        logging:
            driver: none
        command: mongod --quiet --logpath /dev/null

    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "8000:80"