version: '3'

services:
    node_server:
        container_name: node_server
        restart: always
        build: .
        ports:
            - "5000:3000"
        links:
            - db_mongo

    db_mongo:
        container_name: db_mongo
        image: mongo:6.0.2
        ports:
            - "27018:27017"
        volumes:
            - ./mongo/data:/data/db